#if/else --- MOst programming language uses this.

#when

- name: Demo on Conditions
  hosts: localhost
  type: vegetables
  tasks:
    - name: Vegetables
      ansible.builtin.debug:
        msg: vegetables
      when: type == "vegetables"

    - name: Fruits
      ansible.builtin.debug:
        msg: fruits
      when: type == "fruits"  